config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  devise_scope :user do
    delete '/users/:id/delete_avatar', to: 'users/registrations#delete_avatar', as: 'delete_user_avatar'
  end

  resources :profiles, only: [:show] do
    get '/follower_list', to: 'profiles#follower_list', as: "followers"
    get '/following_list', to: 'profiles#following_list', as: "following"
  end

  post 'relationships/create', to: 'relationships#create', as: "follow_user"
  delete 'relationships/destroy', to: 'relationships#destroy', as: "unfollow_user"

  resources :likes, only: [:create, :destroy]
  get 'likes/update', defaults: {format: 'js'}
  
  resources :articles do
    collection do
      get 'user_articles'
    end
    resources :comments, only: [ :create, :edit, :update, :destroy]
  end

  get '/articles/user_articles', to: 'articles#user_articles'

  get '/comments/all_comments', to: 'comments#all_comments',as: 'all_comments'
  patch '/comments/approve_comments', to: 'comments#approve_comments', as: 'approving_comments'

  root 'articles#index'
  
  get 'confirmation_panding', to: "articles#after_registration_path"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # To handle Routing Error
  get '*path', to: 'application#not_found_method', constraints: lambda { |req|
     req.path.exclude?("/rails/active_storage")
    }

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:follower_list, :following_list]

  def show
    @user = User.find(params[:id])
    @articles = @user.articles.select{|article| can?(:read, article)}
  end

  def follower_list
    @followers = @user.followers
  end

  def following_list
    @following = @user.following
  end

  private

  def set_user
    @user = User.find(params[:profile_id])
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/follower_list.html.erb
<div class="container mb-5">
        <table class="table text-light mt-2">
        <thead>
            <tr>
                <th scope="col">User</th>
                <th scope="col">Articles</th>
                <th scope="col">Comments</th>

            </tr>
        </thead>
        <tbody>
            <% @followers.each do |follower| %>
                <tr scope="row">
                    <td><%= link_to follower.username , profile_path(follower), class: "text-light" %></td>
                    <td><%= follower.articles.count %></td>
                    <td><%= follower.comments.count %></td>
                </tr>
            <% end %>
        </tbody>
        </table>
</div>

app/views/profiles/following_list.html.erb
<div class="container mb-5">
        <table class="table text-light mt-2">
        <thead>
            <tr>
                <th scope="col">User</th>
                <th scope="col">Articles</th>
                <th scope="col">Comments</th>

            </tr>
        </thead>
        <tbody>
            <% @following.each do |followee| %>
                <tr scope="row">
                    <td><%= link_to followee.username , profile_path(followee), class: "text-light" %></td>
                    <td><%= followee.articles.count %></td>
                    <td><%= followee.comments.count %></td>
                </tr>
            <% end %>
        </tbody>
        </table>
</div>

app/views/profiles/show.html.erb
<div class="container mt-5">
<section class="section about-section gray-bg" id="about">
    <div class="container">
        <div class="row align-items-center flex-row-reverse">
            <div class="col-lg-6">
                <div class="about-text go-to">
                    <h3 class="dark-color"><%= @user.fullname %></h3>
                    <% if user_signed_in? && @user == current_user %>
                    <h6><%= link_to 'Edit Profile', edit_user_registration_path, class: "theme-color lead link-light" %></h6>
                    <% end %>
                    <h6><%= link_to "Following : #{ @user.following.count }", profile_following_path(@user), class: "link-danger" %> &nbsp;&nbsp;&nbsp;&nbsp; <%= link_to "Followers : #{ @user.followers.count }", profile_followers_path(@user), class: "link-danger" %> </h6>
                    <% if user_signed_in? && @user != current_user %>
                        <% if current_user.following?(@user) %>
                            <%= button_to "Unfollow", unfollow_user_path(user_id: @user.id), method: :delete, class: "btn btn-dark btn-outline-light", style: "opacity: 0.6;" %>
                        <% else %>
                            <%= button_to "Follow", follow_user_path(user_id: @user.id), method: :post, class: "btn btn-danger btn-outline-light", style: "opacity: 0.6;" %>
                        <% end %>
                    <% end %>
                    <div class="row about-list">
                        <div class="col-md-6">
                            <div class="media">
                                <label>Articles</label>
                                <p><%= @user.articles.count %></p>
                            </div>

                            <div class="media">
                                <label>E-mail</label>
                                <p> <%= @user.email %> </p>
                            </div>

                            <div class="media">
                                <label>Birth Date</label>
                                <p> <%= @user.formatted_date %></p>
                            </div>
                            
                            <div class="media">
                                <label>Address</label>
                                <p><%= @user.address %></p>
                            </div>

                            <div class="media">
                                <label>Contect Number</label>
                                <p><%= @user.contact_number %></p>
                            </div>

                            
                        </div>
                        <div class="col-md-6">
                            <div class="media">
                                <label>Comments</label>
                                <p><%= @user.comments.count %></p>
                            </div>

                            <div class="media">
                                <label>Username</label>
                                <p> <%= @user.username %></p>
                            </div>

                            <div class="media">
                                <label>Age</label>
                                <p><%= @user.age %></p>
                            </div>

                            <div class="media">
                                <label>Residence</label>
                                <p><%= @user.country_name%></p>
                            </div>

                            <div class="media">
                                <label>Gender</label>
                                <p><%= @user.gender%></p>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="about-avatar">
                    <% if @user.avatar.attached? %>
                        <%= link_to image_tag(@user.avatar_as_thumbnail), @user.avatar, 
                        style: "opacity: 1;"%>
                        <% if @user == current_user %>
                            <%= button_to 'Delete Profile Picture', delete_user_avatar_path(@user), data: {  confirm: "Are you sure?" }, class: "btn btn-dark btn-outline-light bg-transparent mt-3", method: :delete %>
                        <% end %>
                    <% else %>
                        <img src="https://bootdey.com/img/Content/avatar/avatar7.png", style="opacity: 0.8;">
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</section>
</div>
<div class="container mt-5 mb-5">
    <h4><%= "#{@user.first_name + " " + @user.last_name}'s Articles" %></h4>
    <table class="table text-light mt-2">
        <thead>
            <tr>
                <th scope="col">Article</th>
                <th scope="col">Author</th>
                <th scope="col">Views</th>
                <th scope="col">Status</th>
                <th scope="col">Likes</th>
            </tr>
        </thead>
        <tbody>
            <% @articles.each do |article| %>
                <tr scope="row">
                    <td><%= link_to article.title , article, class: "link-light" %></td>
                    <td><%= article.user.username %></td>
                    <td><%= article.views %></td>
                    <td><%= article.status %></td>
                    <td><%= article.likes.count %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>