config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  devise_scope :user do
    delete '/users/:id/delete_avatar', to: 'users/registrations#delete_avatar', as: 'delete_user_avatar'
  end

  resources :profiles, only: [:show] do
    get '/follower_list', to: 'profiles#follower_list', as: "followers"
    get '/following_list', to: 'profiles#following_list', as: "following"
  end

  post 'relationships/create', to: 'relationships#create', as: "follow_user"
  delete 'relationships/destroy', to: 'relationships#destroy', as: "unfollow_user"

  resources :likes, only: [:create, :destroy]
  get 'likes/update', defaults: {format: 'js'}
  
  resources :articles do
    collection do
      get 'user_articles'
    end
    resources :comments, only: [ :create, :edit, :update, :destroy]
  end

  get '/articles/user_articles', to: 'articles#user_articles'

  get '/comments/all_comments', to: 'comments#all_comments',as: 'all_comments'
  patch '/comments/approve_comments', to: 'comments#approve_comments', as: 'approving_comments'

  root 'articles#index'
  
  get 'confirmation_panding', to: "articles#after_registration_path"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # To handle Routing Error
  get '*path', to: 'application#not_found_method', constraints: lambda { |req|
     req.path.exclude?("/rails/active_storage")
    }

end

app/models/comment.rb
class Comment < ApplicationRecord
  extend FriendlyId
  
  belongs_to :article
  belongs_to :user

  def self.search(search)
    if search
      joins(:user)
      .where("users.username LIKE :search OR 
              users.first_name LIKE :search OR 
              users.last_name LIKE :search OR 
              comments.content LIKE :search
              ", search: "%#{search.strip}%")
    else
      all
    end
  end

  validates :content, presence: true, length: { maximum: 50 }

  friendly_id :content, use: %i[slugged history finders]

  def should_generate_new_friendly_id?
    content_changed? || slug.blank?
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    load_and_authorize_resource
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_article, except: [:all_comments, :approve_comments ]
    before_action :set_comment, only: [:show, :edit, :update, :destroy]


    def all_comments
      @comments = Comment.order('created_at desc').search(params[:search]).select{|comment| can?(:all_comments, comment)}

      if @comments.present?
        @comments = Kaminari.paginate_array(@comments).page(params[:page]).per(8)
      else
        flash[:notice] = "No Result found"
        redirect_to all_comments_path
      end
    end
    
    def approve_comments
      # @comment = Comment.find(params[:id])
      # if @comment.update(params[:approved])
      #   flash[:alert] = "Commets have been Approved"
      #   redirect_to unapproved_comments_path
      # else
      #   flash[:alert] = "Commets have not been Approved"
      #   render :all_unapproved_comments
      # end

      params[:comments].each do |key, value|
        comment = Comment.find(key)
        if value == '1'
          comment.update(approved: true)
        else
          comment.update(approved: false)
        end
      end
      flash[:notice] = "Operation performed successfully"
      redirect_to all_comments_path
    end
  
    def new
      @comment = @article.comments.build
    end
  
    def create
      @comment = @article.comments.build(comment_params)
      @comment.user = current_user
      if @comment.save
        CommentMailer.comment_creation(@comment).deliver_now
        redirect_to article_path(@article)
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @comment.update(comment_params)
        redirect_to article_path(@article)
      else
        render :edit
      end
    end
  
    def destroy
      @comment.destroy

      respond_to do |format|
        format.html { redirect_to article_path(@article), notice: "Comment was successfully destroyed." }
        format.json { head :no_content }
      end

      
    end
  
    private
  
    def set_article
      @article = Article.find(params[:article_id])
    end
  
    def set_comment
      @comment = @article.comments.find(params[:id])
    end
  
    def comment_params
      params.require(:comment).permit(:content)
    end

end
  

app/views/comments/_comment.html.erb
<% if can? :read, comment %>
  <div class="col-sm-6">
    <div class="card bg-transparent text-white m-2" style="width: 18rem;">
      <div class="card-body">
        <p class="card-text">
          <div class="comment">
            <p class="card-text"><%= comment.content %> - <%= link_to comment.user.username, profile_path(comment.user),  class: "link-light" %></p>
            <small><small class="card-text text-muted"> Created <%= time_tag @article.created_at, "data-local": 'time-ago' %> </small></small>
          </div>
          </p>
          
              <p>
              <% if can? :update, comment %>
                <%= link_to 'Edit', edit_article_comment_path(@article, comment), class:"card-link link-light" %> 
              <% end %>
              <% if can? :destroy, comment %>
                <%= button_to "Destroy", article_comment_path(@article, comment),data: { turbo: :false, turbo_confirm: "Are you sure?"}, method: :delete, class: "btn btn-dark btn-outline-light bg-transparent" %>
              <% end %>
              </p>
      </div>
    </div>
  </div>
<% end %>
  

app/views/comments/_form.html.erb
<%= form_with(model:[ @article, comment ] , local: true) do |form| %>

    <% if comment.errors.any? %>
      <div class="alert alert-dark alert-dismissible fade show bg-transparent" role="alert">
        <div id="error_explanation">
          <h2 class="text-light"><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

          <ul>
            <% comment.errors.full_messages.each do |message| %>
              <li class="text-light"><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <% end %>


  <div class="form-group">
    <%= form.label :comment %>
    <%= form.text_area :content, class: "form-control form-control-lg bg-transparent", style: 'color: white;', rows: 4 %>
  </div>

  <div class="d-flex justify-content-left mb-2 mt-2">
    <%= form.submit class:"btn btn-outline-light btn-lg px-5", data: { turbo: false }  %>
  </div>
<% end %>

app/views/comments/all_comments.html.erb
<%= render 'shared/search', path: all_comments_path %>

<div class="container">
    <%= form_with url: approving_comments_path(@comment), method: :patch do |form| %>
        <h3> All Comments </h3>

        <table class="table text-light mt-4">
        <thead>
            <tr>
            <th scope="col">index</th>
            <th scope="col">Comment</th>
            <th scope="col">Commenter</th>
            <th scope="col">Article</th>
            <th scope="col">Author</th>
            <th scope="col">Status</th>
            <th scope="col">Approve</th>
            </tr>
        </thead>
        <tbody>
            <% @comments.each_with_index do |comment,index| %>
                <tr scope="row">
                    <td><%= index+1 %></td>
                    <td><%= comment.content.truncate(20) %></td>
                    <td><%=link_to comment.user.username, profile_path(comment.user), class: "link-light" %></td>
                    <td><%=link_to comment.article.title, article_path(comment.article_id), class: "link-light" %></td>
                    <td><%=link_to comment.article.user.username, profile_path(comment.article.user_id), class: "link-light" %></td>
                    <td><%= comment.article.status  %></td>
                    <td><div class="field">
                        <%= form.check_box "comments[#{comment.id}]", checked: comment.approved %>
                    </div></td>
                </tr>
            <% end %>
        </tbody>
        </table>
        <div class="d-flex justify-content-center mt-3">
            <%= form.submit "Submit", class: 'btn btn-outline-light btn-lg px-5, class: "link-light"' %>
        </div>
    <%end%>

        <div class="container mt-3 mb-3">
            <%= paginate @comments %>
        </div>
</div>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<% if can? :update, Comment %>
    <%= render 'form', comment: @comment %>
<% end %>


<%= link_to 'Back', article_path(@article), class: "link-light" %>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<% if can? :create, Comment %>
    <%= render 'form', comment: @comment %>
<% end %>

<%= link_to 'Back', article_path(@article) %>