config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  devise_scope :user do
    delete '/users/:id/delete_avatar', to: 'users/registrations#delete_avatar', as: 'delete_user_avatar'
  end

  resources :profiles, only: [:show] do
    get '/follower_list', to: 'profiles#follower_list', as: "followers"
    get '/following_list', to: 'profiles#following_list', as: "following"
  end

  post 'relationships/create', to: 'relationships#create', as: "follow_user"
  delete 'relationships/destroy', to: 'relationships#destroy', as: "unfollow_user"

  resources :likes, only: [:create, :destroy]
  get 'likes/update', defaults: {format: 'js'}
  
  resources :articles do
    collection do
      get 'user_articles'
    end
    resources :comments, only: [ :create, :edit, :update, :destroy]
  end

  get '/articles/user_articles', to: 'articles#user_articles'

  get '/comments/all_comments', to: 'comments#all_comments',as: 'all_comments'
  patch '/comments/approve_comments', to: 'comments#approve_comments', as: 'approving_comments'

  root 'articles#index'
  
  get 'confirmation_panding', to: "articles#after_registration_path"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # To handle Routing Error
  get '*path', to: 'application#not_found_method', constraints: lambda { |req|
     req.path.exclude?("/rails/active_storage")
    }

end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId

  validates :title, presence: true, length: { minimum: 3, maximum: 40 }
  validates :subject, presence: true, length: { minimum: 50 }

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  
  has_rich_text :body

  def self.search(search)
    if search
      joins(:user)
      .where("articles.title LIKE :search OR 
              articles.subject LIKE :search OR 
              articles.status LIKE :search OR 
              users.username LIKE :search OR 
              users.first_name LIKE :search OR 
              users.last_name LIKE :search ", 
              search: "%#{search.strip}%")
    else
      all
    end
  end

  friendly_id :title, use: %i[slugged history finders]

  def should_generate_new_friendly_id?
    title_changed? || slug.blank?
  end
  
  
  VALID_STATUSES = ['public', 'private', 'archived']


  validates :status, inclusion: { in: VALID_STATUSES }

  private

  def after_creation
    WelcomeMailer.send_greetings(self).deliver_now
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource  
  before_action :authenticate_user!, except: %i[ index show search ]
  before_action :set_articles, only: %i[ show edit update destroy ]


  def index
      @articles = Article.order('created_at desc').search(params[:search]).select{|article| can?(:read, article)}
      if @articles.present?
        @articles = Kaminari.paginate_array(@articles).page(params[:page]).per(8)
      else
        flash[:notice] = "No Result found"
        redirect_to articles_path
      end
  end

  def user_articles
    @articles = current_user.articles.order('created_at desc').search(params[:search]).page(params[:page]).per(5)
  end

  def show
    @like_exists = Like.where(article: @article, user: current_user) == [] ? false : true
    @article.update( views: @article.views + 1 )
  end

  def new
    @article = current_user.articles.build
  end
  
  def edit
  end
  
  def create
    @article = current_user.articles.build(article_params)
    respond_to do |format|
      if @article.save
        ArticleMailer.article_creation(@article).deliver_now
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else  
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  private
    def set_articles
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :subject, :status, :body)
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <% if @article.errors.any? %>
    <div class="alert alert-dark alert-dismissible fade show bg-transparent" role="alert">
      <div id="error_explanation">
        <h2 class="text-light">
          <%= pluralize(@article.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li  class="text-light"><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
  <div class="card bg-transparent text-white mt-2 mb-3">
    <div class="card-header">
      <div class="row container-fluid">
        <div class="col-sm-6">
          <div class="form-outline">
            <%= form.label :title %><br>
            <%= form.text_field :title, class: "form-control form-control-lg bg-transparent mt-2", style: 'color: white;' %>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="form-outline">
            <%= form.label :status, class:"form-label" %><br>
            <%= form.select :status, ['public', 'private', 'archived'], { include_blank: true }, class: "form-control form-control-lg bg-transparent",  style: 'color: black;' %>
          </div>
        </div>
      </div>
    </div>
    <div class="card-body">
      <p>
        <div class="form-outline">
          <%= form.label :subject %><br>
          <%= form.text_area :subject, class: "form-control form-control-lg bg-transparent ", style: 'color: white;', rows: "15"  %>
        </div>
      </p>
      <p>
        <div class="form-outline">
          <%= form.label :body %><br>
          <%= form.rich_text_area :body, class:"form-control form-control-lg bg-transparent", style: 'color: white;', rows: "15"  %>
        </div>
      </p>
      <div class="d-flex justify-content-center mb-2 mt-2">
        <%= form.submit class:"btn btn-outline-light btn-lg px-5", data: { turbo: false }  %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h2 id="h2"> Edit Article </h2>
<%= link_to "Back", articles_path, class: "link-light" %>
<%= render "form", article: @article %>

app/views/articles/index.html.erb
<%= render 'shared/search', path: articles_path %>

<div class="container mb-5">
    <h3>Articles</h3>
<br>
        <% if can? :create, Article %>
            <%= link_to "New Article", new_article_path, class: "link-light" %>
        <% end %>
        <table class="table text-light mt-4">
        <thead>
            <tr>
                <th scope="col">Article</th>
                <th scope="col">Author</th>
                <th scope="col">Views</th>
                <th scope="col">Status</th>
                <th scope="col">Likes</th>
            </tr>
        </thead>
        <tbody>
            <% @articles.each_with_index do |article,index| %>
                <tr scope="row">
                    <td><%= link_to article.title , article, class: "link-light"%></td>
                    <td><%= article.user.username %></td>
                    <td><%= article.views %></td>
                    <td><%= article.status %></td>
                    <td><%= article.likes.count %></td>
                </tr>
            <% end %>
        </tbody>
        </table>

        <%= paginate @articles %>
</div>

app/views/articles/new.html.erb
<h2> New Article </h2>
<%= link_to "Back", articles_path, class: "link-light" %>
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<div class="container mt-5">
  <div class="card bg-transparent text-white mt-2 mb-5">
    <div class="card-header">
      <div class="row  container-fluid">
        <div class="col-sm-6">
          <h4><%= @article.title %></h4>
          <p>Created by : <%= link_to @article.user.username, profile_path(@article.user),  class: "link-light" %></p>
          <p> <%= @article.views %> Views</p>
          <% if can? :update, @article %>
                <p><%= link_to "Edit", edit_article_path(@article), class: "link-light" %></p> 
            <% end %>
        </div>
        <div class="col-sm-6">
          <p class="text-light text-muted"> Created on : <%= time_tag @article.created_at, "data-local": 'time-ago' %> </p>

            <% if can? :destroy, @article %>
                  <%= button_to "Destroy", article_path(@article),data: { turbo: :false, turbo_confirm: "Are you sure?"}, method: :delete, class: "btn btn-dark btn-outline-light bg-transparent" %>
            <% end %>
          <div>

            <p id="likes_count"><%= pluralize(@article.likes.count, "like") %></p>

              <%= render '/likes/like_button' %>
              <%# <p id= 'likes-count' ><%= pluralize(@article.likes.count, "like")%>
                <% if user_signed_in? %>
                  <%# if can? :update, Like %>
                    <%#= link_to like_text, likes_update_path(article: @article), remote: true, id: "like_link",  class: "btn btn-dark" %>
                  <%# end %>
                  <% if can? :create, Like %>
                  <% like = current_user.likes.find_by(article: @article)  %>
                    <% if like.nil? %>
                        <%= button_to "Like", likes_path(:format => "js"), remote: true, params: { like: { article_id: @article.id } }, method: :post,class: "btn btn-dark btn-outline-light bg-transparent", id: "like_button" %>
                    <% else %>
                        <%= button_to "Unlike", like_path(like,:format => "js"), remote: true,  method: :delete, class: "btn btn-dark btn-outline-light bg-transparent", id: "unlike_button" %>
                    <% end %>
                  <% end %>
                <% end %>

          </div>
        </div>
      </div>
    </div>
    <div class="card-body p-5">
      <div class="card bg-transparent mb-3">
        <div class="card-body p-3">
          <p><%= simple_format(@article.subject) %></p>
        </div>
      </div>
      <% if current_user %>
        <% if @article.comments.exists? %>
        <h5>Comments</h5>
        <% end %>
      <% end %>
      <div class="row">
        <%= render partial: 'comments/comment', collection: @article.comments %>
      </div>
      <div class="container">
        <% if can? :create, Comment %>
          <%= render partial: 'comments/form', locals: { comment: @article.comments.new } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/articles/user_articles.html.erb
<%= render 'shared/search', path: articles_user_articles_path %>

<div class="container mb-5">
    <h3><%= current_user.username %>'s Articles</h3>
<br><br>
        <% if can? :create, Article %>
            <%= link_to "New Article", new_article_path, class: "link-light" %>
        <% end %>
        <table class="table text-light mt-4">
        <thead>
            <tr>
                <th scope="col">Article</th>
                <th scope="col">Author</th>
                <th scope="col">Views</th>
                <th scope="col">Status</th>
                <th scope="col">Likes</th>
            </tr>
        </thead>
        <tbody>
            <% @articles.each do |article| %>
                <tr scope="row">
                    <td><%= link_to article.title , article, class: "link-light"%></td>
                    <td><%= article.user.username %></td>
                    <td><%= article.views %></td>
                    <td><%= article.status %></td>
                    <td><%= article.likes.count %></td>
                </tr>
            <% end %>
        </tbody>
        </table>

        <%= paginate @articles %>
</div>