config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  devise_scope :user do
    delete '/users/:id/delete_avatar', to: 'users/registrations#delete_avatar', as: 'delete_user_avatar'
  end

  resources :profiles, only: [:show] do
    get '/follower_list', to: 'profiles#follower_list', as: "followers"
    get '/following_list', to: 'profiles#following_list', as: "following"
  end

  post 'relationships/create', to: 'relationships#create', as: "follow_user"
  delete 'relationships/destroy', to: 'relationships#destroy', as: "unfollow_user"

  resources :likes, only: [:create, :destroy]
  get 'likes/update', defaults: {format: 'js'}
  
  resources :articles do
    collection do
      get 'user_articles'
    end
    resources :comments, only: [ :create, :edit, :update, :destroy]
  end

  get '/articles/user_articles', to: 'articles#user_articles'

  get '/comments/all_comments', to: 'comments#all_comments',as: 'all_comments'
  patch '/comments/approve_comments', to: 'comments#approve_comments', as: 'approving_comments'

  root 'articles#index'
  
  get 'confirmation_panding', to: "articles#after_registration_path"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # To handle Routing Error
  get '*path', to: 'application#not_found_method', constraints: lambda { |req|
     req.path.exclude?("/rails/active_storage")
    }

end

app/views/shared/_errors.html.erb
<% if notice %>
    <div class="container">
        <div class="alert alert-dark alert-dismissible fade show bg-transparent" role="alert">
            <p class="notice text-light"><%= notice %></p>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
<% elsif alert %>
        <div class="alert alert-dark alert-dismissible fade show bg-transparent" role="alert">
            <p class="alert text-light"><%= alert %></p>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark shadow-5-strong">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Blogs</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Articles", articles_path, class: "nav-link" %>
        </li>
        <% if can? :all_comments, Comment %>
        <li class="nav-item">
            <%= link_to "Approver Console", all_comments_path, class: "nav-link" %>
        </li>
        <% end %>
        <% if can? :create, Article %>
        <% if current_user %>
        <li class="nav-item">
            <%= link_to "Your Articles", articles_user_articles_path(@user), class: "nav-link" %>
        </li>
        <% end %>
        <% end %>
      </ul>

      <ul class = "navbar-nav ms-auto mb-2 mb-lg-0">
         <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <li class="nav-item mt-3 text-light">Hello <%= current_user.fullname %></li>
            <%= render 'shared/photo' %>
            <ul class="dropdown-menu dropdown-menu-lg-end bg-transparent">
              <li><%= link_to "Profile", profile_path(current_user), class: "dropdown-item text-light" %></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item text-light" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= button_to "Logout", destroy_user_session_path, class: "dropdown-item btn btn-light text-light", method: :delete %></li>
            </ul>
          </li>
          <% else %>
          <li class = "nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
          </li>
          <li class = "nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
          <% end %>
      </ul>

        
    </div>
  </div>
</nav>

<pre>


</pre>

app/views/shared/_photo.html.erb
<% if current_user.avatar.attached? %>
    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <%= image_tag(current_user.avatar_as_thumbnail, style: "display: inline-block;
                                                              width: 40px;
                                                              height: 40px;
                                                              object-fit: cover;
                                                              border-radius: 50%;") %>
    </a>
<% elsif current_user.gender == 'male'%>
    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <%= image_tag("male.png", style: "display: inline-block;
                                        width: 40px;
                                        height: 40px;
                                        object-fit: cover;
                                        border-radius: 50%;") %>
    </a>
<% elsif current_user.gender == 'female'%>
    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <%= image_tag("female.png", style: "display: inline-block;
                                          width: 40px;
                                          height: 40px;
                                          object-fit: cover;
                                          border-radius: 50%;") %>
    </a>
<% else %>
    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <%= image_tag("unknown.jpg", style: "display: inline-block;
                                             width: 40px;
                                             height: 40px;
                                             object-fit: cover;
                                             border-radius: 50%;") %>
      </a>
<% end %>

app/views/shared/_search.html.erb
<style>
.search{
  display: flex;
}
</style>

<div class="container mt-2 mb-3">
    <%= form_tag(path, method: :get, class: "search" ) do %>
        <%= search_field_tag :search , params[:search], class:"form-control form-control-lg bg-transparent me-2", style: 'color: white;', placeholder: "Search Here" %>
        <%= submit_tag "Search", class:"btn btn-outline-light btn-lg px-5 mt-1 ms-2" %>
    <% end %>
</div>